pipeline {
	agent any

	stages {
		stage('Unit tests - backend') {
			steps {
				dir('bugtracker-backend') {
					sh 'go test -v ./...'
				}
			}
		}
		stage('ui tests - frontend') {
			agent any
			steps {
				dir('bugtracker-frontend') {
					sh '''
						# Проверяем Node.js
						if ! command -v node &> /dev/null; then
							echo "Node.js не найден, устанавливаем..."
							# Установка Node.js для Debian/Ubuntu
							curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
							apt-get install -y nodejs
						fi

						npm ci
						npm test
					'''
				}
			}
		}
	}
}